from __future__ import annotations

from image_to_editable_ppt.ml.adapter import AnnotationMLAdapter, DetectorModelOutput, MLAdapter
from image_to_editable_ppt.ml.annotation_schema import (
    AnnotationBBox,
    AnnotationConnectorCandidate,
    AnnotationConnectorEndpoint,
    AnnotationContainer,
    AnnotationDiagramInstance,
    AnnotationFamilyProposal,
    AnnotationImageSize,
    AnnotationNode,
    AnnotationPort,
    AnnotationPrimitiveScene,
    AnnotationPrimitiveText,
    AnnotationResidual,
    AnnotationSchemaError,
    AnnotationTextRegion,
    DetectorAnnotationDocument,
    annotation_to_json,
)
from image_to_editable_ppt.ml.metrics import (
    DetectorEvaluationReport,
    DetectorMetrics,
    DetectionMetrics,
    FamilyProposalMetrics,
    evaluate_detector_predictions,
)

__all__ = [
    "AnnotationBBox",
    "AnnotationConnectorCandidate",
    "AnnotationConnectorEndpoint",
    "AnnotationContainer",
    "AnnotationDiagramInstance",
    "AnnotationFamilyProposal",
    "AnnotationImageSize",
    "AnnotationMLAdapter",
    "AnnotationNode",
    "AnnotationPort",
    "AnnotationPrimitiveScene",
    "AnnotationPrimitiveText",
    "AnnotationResidual",
    "AnnotationSchemaError",
    "AnnotationTextRegion",
    "DetectorAnnotationDocument",
    "DetectorEvaluationReport",
    "DetectorMetrics",
    "DetectorModelOutput",
    "DetectionMetrics",
    "FamilyProposalMetrics",
    "MLAdapter",
    "annotation_to_json",
    "evaluate_detector_predictions",
]
