from __future__ import annotations

from image_to_editable_ppt.ml.adapter import AnnotationMLAdapter, DetectorModelOutput, MLAdapter
from image_to_editable_ppt.ml.annotation_schema import (
    AnnotationBBox,
    AnnotationConnectorCandidate,
    AnnotationConnectorEndpoint,
    AnnotationContainer,
    AnnotationDiagramInstance,
    AnnotationFamilyProposal,
    AnnotationImageSize,
    AnnotationNode,
    AnnotationPort,
    AnnotationPrimitiveScene,
    AnnotationPrimitiveText,
    AnnotationResidual,
    AnnotationSchemaError,
    AnnotationTextRegion,
    DetectorAnnotationDocument,
    annotation_to_json,
)
from image_to_editable_ppt.ml.generate_dataset import (
    GenerateDatasetConfig,
    assign_splits,
    build_dataset,
)
from image_to_editable_ppt.ml.metrics import (
    ConnectorAttachmentMetrics,
    DetectorEvaluationReport,
    DetectorMetrics,
    DetectionMetrics,
    FamilyProposalMetrics,
    StructuralExactness,
    evaluate_detector_predictions,
)
from image_to_editable_ppt.ml.synthesize import (
    GENERATOR_NAME,
    RENDERER_NAME,
    SUPPORTED_FAMILIES,
    SyntheticSlideSpec,
    generate_slide_spec,
    render_spec_image,
    validate_spec_contract,
    write_spec_pptx,
)

__all__ = [
    "AnnotationBBox",
    "AnnotationConnectorCandidate",
    "AnnotationConnectorEndpoint",
    "AnnotationContainer",
    "AnnotationDiagramInstance",
    "AnnotationFamilyProposal",
    "AnnotationImageSize",
    "AnnotationMLAdapter",
    "AnnotationNode",
    "AnnotationPort",
    "AnnotationPrimitiveScene",
    "AnnotationPrimitiveText",
    "AnnotationResidual",
    "AnnotationSchemaError",
    "AnnotationTextRegion",
    "ConnectorAttachmentMetrics",
    "DetectorAnnotationDocument",
    "DetectorEvaluationReport",
    "DetectorMetrics",
    "DetectorModelOutput",
    "DetectionMetrics",
    "FamilyProposalMetrics",
    "GENERATOR_NAME",
    "GenerateDatasetConfig",
    "MLAdapter",
    "RENDERER_NAME",
    "SUPPORTED_FAMILIES",
    "StructuralExactness",
    "SyntheticSlideSpec",
    "annotation_to_json",
    "assign_splits",
    "evaluate_detector_predictions",
    "build_dataset",
    "generate_slide_spec",
    "render_spec_image",
    "validate_spec_contract",
    "write_spec_pptx",
]
